### ISSUE TITLE
NEED CONFIRMATION on  STRUCTURE SCHEMA fields

### ISSUE THREAD

**Issue by julietsitron** [NYCParks-data/Structures#31]
**fields to review, communicate final decision to SG (and add to GitHub if staying):**
- ~~Historic~~
- ~~Jurisdiction~~
- ~~Comments~~

**fields to review (and add to GitHub if staying):**
 - ~~Name~~
 - ~~SignName~~
 
**fields to be removed (please confirm):**
 - ~~Retired~~
 - ~~RetiredDate~~
 - ~~Sub_Category~~

**fields to add to GitHub:**
 - ~~OMPPropID~~
 -  ~~Alteration_Year~~

**fields to remove from GitHub:**
- ~~Site_Name~~

**fields to change spelling on GitHub for consistency:**
- ~~CommissionDate~~
- ~~COStatus~~
- ~~CriticalityClass~~
- ~~MaintBy~~
- ~~MaintBySpec~~

**Comment by GeoDan87** [comment]
Removed Site_Name, updated spelling and added columns back. https://github.com/NYCParks-data/Structures/wiki/Structure-Schema/e302362b0a976cff5fc59eaa5a93d87aae38f9a1

**Comment by GeoDan87** [comment]
Jurisdiction and comments added. https://github.com/NYCParks-data/Structures/wiki/Structure-Schema/79c8941c3326cc05bf75d1b9e3b3459be0d65fec

**Comment by GeoDan87** [comment]
With confirmation of deletion of Name and Signname this issue is closed
